version: '3.9'
services:
  frontend:
    container_name: frontend-delivery
    build: './front-end'
    tty: true
    ports:
      - 3000:3000
    working_dir: /app-frontend
    restart: 'always'
    volumes:
      - ./front-end/src:/app-frontend/src
      - ./front-end/package.json:/app-frontend/package.json
    depends_on:
      - backend
  backend:
    container_name: backend-delivery
    build: ./back-end
    ports:
      - 3001:3001
    tty: true
    working_dir: /app-backend
    command: xablau
    restart: 'always'
    volumes:
      - ./back-end/src:/app-backend/src
      - ./back-end/package.json:/app-backend/package.json
    environment:
      - HOSTNAME=db
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.21
    container_name: db-delivery
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3002:3306
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
    default:
        driver: bridge
